### ISSUE TITLE
In the yaml, if rsocket.brokers is list, `RSocketBrokerHealthIndicator` is not registered.

### ISSUE THREAD

**Issue by amondnet** [alibaba/alibaba-rsocket-broker#239]
**Describe the bug**

In the yaml, if `rsocket.brokers` is a list, then `RSocketBrokerHealthIndicator` is not registered.

```yaml
    rsocket:
      brokers: 
      - tcp://localhost:9999
```

 If it is a string, then `RSocketBrokerHealthIndicator` is registered.

```yaml
    rsocket:
      brokers: tcp://localhost:9999
```

### Environment

* Alibaba RSocket Broker version: 1.1.5
* Operating System version: Mac
* Java version: 17

### Steps to reproduce this issue

1. set rsocket.brokers to list
    ```yaml
    rsocket:
      brokers: 
      - tcp://localhost:9999
    management:
      endpoint:
        health:
          show-details: always      
    ```
2. bootRun
3. open `http://localhost:8080/actuator/health`

Pls. provide GitHub address to reproduce this issue.

### Expected Result

```json
{
  "status": "DOWN",
  "components": {
   "mongo": {
      "status": "UP",
      "details": {
        "maxWireVersion": 17
      }
    },
    "ping": {
      "status": "UP"
    },
    "r2dbc": {
      "status": "UP",
      "details": {
        "database": "MariaDB",
        "validationQuery": "validate(REMOTE)"
      }
    },
    "rsocketBrokerHealth": {
      "status": "DOWN",
      "details": {
        "brokers": "tcp://localhost:9999"
      }
    }
  }
}
```

### Actual Result

```json
{
  "status": "UP",
  "components": {
    "mongo": {
      "status": "UP",
      "details": {
        "maxWireVersion": 17
      }
    },
    "ping": {
      "status": "UP"
    },
    "r2dbc": {
      "status": "UP",
      "details": {
        "database": "MariaDB",
        "validationQuery": "validate(REMOTE)"
      }
    }
  }
}
```

**Comment by shareisall** [comment]
rsocket.broker.topology=gossip
rsocket.broker.seeds=192.168.1.2,192.168.1.3,192.168.1.4

**Comment by amondnet** [comment]
@shareisall 

> rsocket.broker.topology=gossip
> rsocket.broker.seeds=192.168.1.2,192.168.1.3,192.168.1.4

The above properties are used by the `alibaba-rsocket-server`. This issue occurs in `alibaba-rsocket-spring-boot-starter.`.

https://github.com/alibaba/alibaba-rsocket-broker/blob/fdd39b328b6ed69d7b2e320d8384f29bdc189569/alibaba-rsocket-spring-boot-starter/src/main/java/com/alibaba/spring/boot/rsocket/RSocketAutoConfiguration.java#L166
```java
    @Bean
    @ConditionalOnProperty("rsocket.brokers")
    public RSocketBrokerHealthIndicator rsocketBrokerHealth(RSocketEndpoint rsocketEndpoint, UpstreamManager upstreamManager, @Value("${rsocket.brokers}") String brokers) {
        return new RSocketBrokerHealthIndicator(rsocketEndpoint, upstreamManager, brokers);
    }
```

If you use `application.properties` or `application.yaml` + string, the `RSocketBrokerHealthIndicator` will be registered without any problems.

```properties
rsocket.brokers=tcp://localhost:9999
```
```yaml
rsocket:
  brokers: tcp://localhost:9999
```

However, if you use an array of strings, it won't register.

```yaml
rsocket:
  brokers:
  - tcp://localhost:9999
```

This is fine for practical use, but kubernetes scheduler can't perform health checks properly because the health indicator is not registered.

**Comment by shareisall** [comment]
Sorry for last reply. But it works for me.

### Envirements:
- SpringBoot 3.1.4
- Alibaba RSocket Broker version: 1.1.5
- Operating System version: Mac
- Java version: 17

### Code:
```
rsocket:
  brokers:
    - tcp://127.0.0.1:9999
    - tcp://127.0.0.1:9999
  jwt-token: None
```
